#!/bin/bash
# Fix Xcode build by generating Flutter files first

cd "$(dirname "$0")"

echo "🔧 Fixing Xcode build issues..."
echo ""

# Step 1: Clean Flutter
echo "1. Cleaning Flutter..."
flutter clean

# Step 2: Get dependencies
echo "2. Getting Flutter dependencies..."
flutter pub get

# Step 3: Ensure ephemeral directory exists
echo "3. Creating ephemeral files..."
mkdir -p ios/Flutter/ephemeral

# Step 4: Create placeholder files (Flutter will populate them)
echo "# Flutter input files - generated by Flutter" > ios/Flutter/ephemeral/FlutterInputs.xcfilelist
echo "# Flutter output files - generated by Flutter" > ios/Flutter/ephemeral/FlutterOutputs.xcfilelist

# Step 5: Generate Flutter files
echo "4. Generating Flutter iOS files..."
flutter precache --ios

# Step 6: Try to build (this will generate all necessary files)
echo "5. Building iOS (this generates Flutter files)..."
flutter build ios --no-codesign 2>&1 | head -30 || echo "Build may have issues, but files should be generated"

echo ""
echo "✅ Done! Now try building in Xcode:"
echo "   - Open: ios/Runner.xcworkspace"
echo "   - Product → Clean Build Folder (Shift+Cmd+K)"
echo "   - Product → Build (Cmd+B)"



