// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE3PuK3LibB3ePBNWE55k3E9E2RyzMqJY',
    appId: '1:137587508919:web:dc26ff430c36df769baf32',
    messagingSenderId: '137587508919',
    projectId: 'wandermood-7e33b',
    authDomain: 'wandermood-7e33b.firebaseapp.com',
    storageBucket: 'wandermood-7e33b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ9dVFf3HFgDIIXG2IQlXl09_7jGP3QCg',
    appId: '1:137587508919:android:54ce836cc0fb5ad49baf32',
    messagingSenderId: '137587508919',
    projectId: 'wandermood-7e33b',
    storageBucket: 'wandermood-7e33b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC15ySBD_kcQ4lvuW_u1Wol1SI7ns9dfPY',
    appId: '1:137587508919:ios:fd6a916e46f8c94d9baf32',
    messagingSenderId: '137587508919',
    projectId: 'wandermood-7e33b',
    storageBucket: 'wandermood-7e33b.firebasestorage.app',
    iosBundleId: 'com.edviennemer.wandermood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC15ySBD_kcQ4lvuW_u1Wol1SI7ns9dfPY',
    appId: '1:137587508919:ios:bcf92fe1bf6e40089baf32',
    messagingSenderId: '137587508919',
    projectId: 'wandermood-7e33b',
    storageBucket: 'wandermood-7e33b.firebasestorage.app',
    iosBundleId: 'com.example.wandermood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAE3PuK3LibB3ePBNWE55k3E9E2RyzMqJY',
    appId: '1:137587508919:web:c500df0b263d05ce9baf32',
    messagingSenderId: '137587508919',
    projectId: 'wandermood-7e33b',
    authDomain: 'wandermood-7e33b.firebaseapp.com',
    storageBucket: 'wandermood-7e33b.firebasestorage.app',
  );
}
